[constants]
SAMPLE_RATE = 16000
CHUNK_SIZE = 1600
SAMPLE_WIDTH = 2
VAD_THRESHOLD = 1e-5
FREQ_THRESHOLD = 100.0
STEP_MS = 0
LENGTH_MS = 4000
VAD_WINDOW_SIZE_MS = 1000
MODEL_NAME = "large-v3-turbo"
BATCH_SIZE = 12
QUANT = 'None'